package crypto

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
)

// randomTokenBytes is the entropy backing every opaque token generated by
// GenerateOpaqueToken: 256 bits, comfortably beyond what's
// brute-forceable, consistent with treating these tokens as high-entropy
// (see HashToken's doc comment on why a fast hash is acceptable for them
// but not for passwords).
const randomTokenBytes = 32

// GenerateOpaqueToken returns a new random opaque token in the form
// "<prefix><base64url>", e.g. "vgs_xyz..." for machine tokens or
// "vgs_sess_xyz..." for session tokens. The prefix makes the token's
// purpose recognizable at a glance in logs, accidental commits, and secret
// scanners.
func GenerateOpaqueToken(prefix string) (string, error) {
	raw := make([]byte, randomTokenBytes)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("crypto: generate opaque token: %w", err)
	}
	return prefix + base64.RawURLEncoding.EncodeToString(raw), nil
}
